-
  name: 'Order API'
  uriPattern: 'api/order'
  defaults:
    '@package': 'ISP.Carteo'
    '@controller': 'Order'
    '@action': 'submit'
-
  name: 'WhatsApp Webhook Verify'
  uriPattern:  'api/webhook'
  httpMethods: ['GET']
  defaults:
    '@package':    'ISP.Carteo'
    '@controller': 'Webhook'
    '@action':     'verify'
    '@format':     'json'

-
  name: 'WhatsApp Webhook Receive'
  uriPattern:  'api/webhook'
  httpMethods: ['POST']
  defaults:
    '@package':    'ISP.Carteo'
    '@controller': 'Webhook'
    '@action':     'receive'
    '@format':     'json'
