Neos:  
  Neos:    
    fusion:
      autoInclude:
        'ISP.Carteo': true  
    dataSources:
      isp-carteo-menus:
        className: ISP\Carteo\DataSources\MenuDataSource       
    nodeTypes:
      groups:
        carteo:
          position: 10
          label: 'Carteo'
          collapsed: true
    modules:

    modules:
      isp-carteo:
        label: 'Carteo'
        controller: 'ISP\Carteo\Controller\OverviewController'
        description: 'Moderne Menüverwaltung'
        icon: icon-clipboard-list
        submodules:
          'managerModule':
            label: 'Carteo Manager'
            controller: 'ISP\Carteo\Controller\ManagerController'
            description: 'Mit diesem Modul kann die Speisekarte aktualisiert und exportiert werden.'
            icon: icon-list
            additionalResources:
              javaScripts:
                - resource://ISP.Carteo/Public/JavaScript/backend.js              
              styleSheets:
                - resource://ISP.Carteo/Public/Styles/backend.css
          'studioModule':
            label: 'Carteo Studio'
            controller: 'ISP\Carteo\Controller\StudioController'
            description: 'Mit diesem Modul kann die Speisekarte aktualisiert und exportiert werden.'
            icon: icon-print
            additionalResources:
              javaScripts:
                - resource://ISP.Carteo/Public/JavaScript/backend.js              
              styleSheets:
                - resource://ISP.Carteo/Public/Styles/backend.css
          'orderModule':
            label: 'Bestellübersicht'
            controller: 'ISP\Carteo\Controller\OrderController'
            description: 'Mit diesem Modul können Bestellungen eingesehen und verwaltet werden.'
            icon: icon-euro-sign
            additionalResources:
              javaScripts:
                - resource://ISP.Carteo/Public/JavaScript/backend.js              
              styleSheets:
                - resource://ISP.Carteo/Public/Styles/backend.css
ISP:
  Carteo:
    styling:
      pdf:
        css: 'resource://ISP.Carteo/Public/Styles/menuPdfStyling.css'
        backgroundImage: 'resource://ISP.Carteo/Public/Images/menu-bg.png'
        logo: 'resource://ISP.Carteo/Public/Images/carteo_logo.png'
